basePath: /
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server Petstore server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /users:
    get:
      consumes:
      - application/json
      description: Get all users
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: Get all users
    post:
      consumes:
      - application/json
      description: this to create a user
      parameters:
      - description: Person Data
        in: body
        name: persondata
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: Create user
  /users/{email}:
    delete:
      consumes:
      - application/json
      description: this to delete a user by email
      parameters:
      - description: Some ID
        in: path
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: Delete user
    get:
      consumes:
      - application/json
      description: this to get a user by email
      parameters:
      - description: Some ID
        in: path
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: Get user
    patch:
      consumes:
      - application/json
      description: this to update a user by email
      parameters:
      - description: Some ID
        in: path
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: Update user
swagger: "2.0"
